import { ConversationTurn } from '../../types';

// ── Per-language greeting conversation scripts ─────────────────────────────
// Each script is a full 4-turn greeting exchange:
//   Guide greets user by name → User responds → Guide asks "How are you?" → User replies
// All native phrases are accurate. Distractors are real phrases (just wrong context).

type LangScript = (name: string) => ConversationTurn[];

const scripts: Record<string, LangScript> = {

  swahili: (name) => [
    {
      speaker: 'guide',
      text: `Hujambo, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Sijambo!',
      textTranslation: "I'm fine! (reply to Hujambo)",
      textTranslationFr: 'Je vais bien ! (réponse à Hujambo)',
      options: ['Sijambo!', 'Kwaheri!', 'Asante!'],
      optionsFr: ['Sijambo !', 'Kwaheri !', 'Asante !'],
      correctIndex: 0,
      wrongExplanation: '"Sijambo!" is the correct reply to "Hujambo". "Kwaheri" means goodbye, and "Asante" means thank you.',
      wrongExplanationFr: '"Sijambo !" est la bonne réponse à "Hujambo". "Kwaheri" signifie au revoir et "Asante" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Habari yako?',
      textTranslation: 'How are you? (your news?)',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Nzuri sana, asante! Na wewe?',
      textTranslation: 'Very good, thanks! And you?',
      textTranslationFr: 'Très bien, merci ! Et toi ?',
      options: ['Nzuri sana, asante! Na wewe?', 'Sijui.', 'Kwaheri, rafiki!'],
      optionsFr: ['Nzuri sana, asante ! Na wewe ?', 'Sijui.', 'Kwaheri, rafiki !'],
      correctIndex: 0,
      wrongExplanation: '"Nzuri sana, asante!" means "Very good, thank you!" — the polite way to reply. "Sijui" means "I don\'t know" and "Kwaheri" means goodbye.',
      wrongExplanationFr: '"Nzuri sana, asante !" signifie "Très bien, merci !" — la façon polie de répondre.',
    },
  ],

  hausa: (name) => [
    {
      speaker: 'guide',
      text: `Sannu, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Sannu!',
      textTranslation: 'Hello! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Sannu!', 'Sai anjima!', 'Na gode!'],
      optionsFr: ['Sannu !', 'Sai anjima !', 'Na gode !'],
      correctIndex: 0,
      wrongExplanation: '"Sannu!" is the correct greeting reply. "Sai anjima" means see you later, and "Na gode" means thank you.',
      wrongExplanationFr: '"Sannu !" est la bonne réponse. "Sai anjima" signifie à bientôt et "Na gode" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Yaya lafiya?',
      textTranslation: 'How is your health?',
      textTranslationFr: 'Comment va votre santé ?',
    },
    {
      speaker: 'user',
      text: 'Lafiya lau. Kai kuwa?',
      textTranslation: "I'm perfectly well. And you?",
      textTranslationFr: 'Je vais très bien. Et toi ?',
      options: ['Lafiya lau. Kai kuwa?', 'Ban sani ba.', 'Sai anjima!'],
      optionsFr: ['Lafiya lau. Kai kuwa ?', 'Ban sani ba.', 'Sai anjima !'],
      correctIndex: 0,
      wrongExplanation: '"Lafiya lau" means "perfectly well/fine" — the standard reply to "Yaya lafiya?" "Ban sani ba" means "I don\'t know."',
      wrongExplanationFr: '"Lafiya lau" signifie "très bien" — la réponse habituelle à "Yaya lafiya ?"',
    },
  ],

  yoruba: (name) => [
    {
      speaker: 'guide',
      text: `Ẹ káàárọ̀, ${name}!`,
      textTranslation: `Good morning, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Ẹ káàárọ̀!',
      textTranslation: 'Good morning! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Ẹ káàárọ̀!', 'Ó dàbọ̀!', 'Ẹ séun!'],
      optionsFr: ['Ẹ káàárọ̀ !', 'Ó dàbọ̀ !', 'Ẹ séun !'],
      correctIndex: 0,
      wrongExplanation: '"Ẹ káàárọ̀" is the correct morning greeting reply. "Ó dàbọ̀" means goodbye, and "Ẹ séun" means thank you.',
      wrongExplanationFr: '"Ẹ káàárọ̀" est la bonne réponse au salut du matin. "Ó dàbọ̀" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'Báwo ni?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Mo wà dáadáa, ẹ séun! Ẹ nkọ?',
      textTranslation: "I'm fine, thank you! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et vous ?',
      options: ['Mo wà dáadáa, ẹ séun! Ẹ nkọ?', "Mi ò mọ̀.", 'Ó dàbọ̀, ọ̀rẹ́!'],
      optionsFr: ['Mo wà dáadáa, ẹ séun ! Ẹ nkọ ?', 'Mi ò mọ̀.', 'Ó dàbọ̀, ọ̀rẹ́ !'],
      correctIndex: 0,
      wrongExplanation: '"Mo wà dáadáa" means "I am fine." "Mi ò mọ̀" means "I don\'t know" and "Ó dàbọ̀" means goodbye.',
      wrongExplanationFr: '"Mo wà dáadáa" signifie "Je vais bien." "Mi ò mọ̀" signifie "Je ne sais pas".',
    },
  ],

  igbo: (name) => [
    {
      speaker: 'guide',
      text: `Ndewo, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Ndewo!',
      textTranslation: 'Hello! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Ndewo!', 'Ọ dị mma!', 'Daalu!'],
      optionsFr: ['Ndewo !', 'Ọ dị mma !', 'Daalu !'],
      correctIndex: 0,
      wrongExplanation: '"Ndewo!" is the correct greeting reply. "Ọ dị mma" means it is fine/okay, and "Daalu" means thank you.',
      wrongExplanationFr: '"Ndewo !" est la bonne réponse. "Ọ dị mma" signifie c\'est bien, et "Daalu" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Kedu ka ị dị?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'A dị m mma. Gị kwa?',
      textTranslation: "I'm fine. And you?",
      textTranslationFr: 'Je vais bien. Et toi ?',
      options: ['A dị m mma. Gị kwa?', 'Amaghị m.', 'Ka ọ dị!'],
      optionsFr: ['A dị m mma. Gị kwa ?', 'Amaghị m.', 'Ka ọ dị !'],
      correctIndex: 0,
      wrongExplanation: '"A dị m mma" means "I am fine." "Amaghị m" means "I don\'t know" and "Ka ọ dị" means goodbye.',
      wrongExplanationFr: '"A dị m mma" signifie "Je vais bien." "Ka ọ dị" signifie au revoir.',
    },
  ],

  zulu: (name) => [
    {
      speaker: 'guide',
      text: `Sawubona, ${name}!`,
      textTranslation: `Hello, ${name}! (I see you)`,
      textTranslationFr: `Bonjour, ${name} ! (je te vois)`,
    },
    {
      speaker: 'user',
      text: 'Yebo, sawubona!',
      textTranslation: 'Yes, hello! (I see you too)',
      textTranslationFr: 'Oui, bonjour ! (je te vois aussi)',
      options: ['Yebo, sawubona!', 'Hamba kahle!', 'Ngiyabonga!'],
      optionsFr: ['Yebo, sawubona !', 'Hamba kahle !', 'Ngiyabonga !'],
      correctIndex: 0,
      wrongExplanation: '"Yebo, sawubona!" means "Yes, hello!" — the proper reply. "Hamba kahle" means go well (farewell), "Ngiyabonga" means thank you.',
      wrongExplanationFr: '"Yebo, sawubona !" est la bonne réponse. "Hamba kahle" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'Unjani?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Ngikhona, ngiyabonga! Wena unjani?',
      textTranslation: "I'm here, thank you! How are you?",
      textTranslationFr: 'Je suis là, merci ! Et toi ?',
      options: ['Ngikhona, ngiyabonga! Wena unjani?', 'Angazi.', 'Sala kahle!'],
      optionsFr: ['Ngikhona, ngiyabonga ! Wena unjani ?', 'Angazi.', 'Sala kahle !'],
      correctIndex: 0,
      wrongExplanation: '"Ngikhona" means "I am here/fine." "Angazi" means "I don\'t know" and "Sala kahle" means stay well (goodbye).',
      wrongExplanationFr: '"Ngikhona" signifie "Je vais bien." "Sala kahle" signifie au revoir.',
    },
  ],

  amharic: (name) => [
    {
      speaker: 'guide',
      text: `ሰላም, ${name}!`,
      textTranslation: `Hello (Peace), ${name}!`,
      textTranslationFr: `Bonjour (Paix), ${name} !`,
    },
    {
      speaker: 'user',
      text: 'ሰላም!',
      textTranslation: 'Hello! (Peace!)',
      textTranslationFr: 'Bonjour ! (Paix !)',
      options: ['ሰላም!', 'አመሰግናለሁ!', 'ደህና ሁን!'],
      optionsFr: ['ሰላም !', 'አመሰግናለሁ !', 'ደህና ሁን !'],
      correctIndex: 0,
      wrongExplanation: '"ሰላም!" (Selam) is the correct greeting back. "አመሰግናለሁ" means thank you, and "ደህና ሁን" means goodbye.',
      wrongExplanationFr: '"ሰላም !" (Selam) est la bonne réponse. "አመሰግናለሁ" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'ደህና ነህ?',
      textTranslation: 'Are you well?',
      textTranslationFr: 'Allez-vous bien ?',
    },
    {
      speaker: 'user',
      text: 'ደህና ነኝ, አመሰግናለሁ! አንተስ?',
      textTranslation: "I'm well, thank you! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et toi ?',
      options: ['ደህና ነኝ, አመሰግናለሁ! አንተስ?', 'አላውቅም.', 'ደህና ሁን!'],
      optionsFr: ['ደህና ነኝ, አመሰግናለሁ ! አንተስ ?', 'አላውቅም.', 'ደህና ሁን !'],
      correctIndex: 0,
      wrongExplanation: '"ደህና ነኝ" means "I am well." "አላውቅም" means "I don\'t know" and "ደህና ሁን" means goodbye.',
      wrongExplanationFr: '"ደህና ነኝ" signifie "Je vais bien." "ደህና ሁን" signifie au revoir.',
    },
  ],

  arabic: (name) => [
    {
      speaker: 'guide',
      text: `أهلاً، ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'أهلاً وسهلاً!',
      textTranslation: 'Welcome! (reply to أهلاً)',
      textTranslationFr: 'Bienvenue ! (réponse à أهلاً)',
      options: ['أهلاً وسهلاً!', 'مع السلامة!', 'شكراً!'],
      optionsFr: ['أهلاً وسهلاً !', 'مع السلامة !', 'شكراً !'],
      correctIndex: 0,
      wrongExplanation: '"أهلاً وسهلاً" is the classic reply to "أهلاً". "مع السلامة" means goodbye, and "شكراً" means thank you.',
      wrongExplanationFr: '"أهلاً وسهلاً" est la réponse classique. "مع السلامة" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'كيف حالك؟',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'بخير، شكراً! وأنت؟',
      textTranslation: 'Fine, thank you! And you?',
      textTranslationFr: 'Bien, merci ! Et toi ?',
      options: ['بخير، شكراً! وأنت؟', 'لا أعرف.', 'مع السلامة!'],
      optionsFr: ['بخير، شكراً ! وأنت ?', 'لا أعرف.', 'مع السلامة !'],
      correctIndex: 0,
      wrongExplanation: '"بخير" means "fine/well" — the standard reply to "كيف حالك?". "لا أعرف" means "I don\'t know."',
      wrongExplanationFr: '"بخير" signifie "bien" — la réponse habituelle à "كيف حالك?". "لا أعرف" signifie "je ne sais pas".',
    },
  ],

  shona: (name) => [
    {
      speaker: 'guide',
      text: `Mhoro, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Mhoro!',
      textTranslation: 'Hello! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Mhoro!', 'Chisarai!', 'Ndinotenda!'],
      optionsFr: ['Mhoro !', 'Chisarai !', 'Ndinotenda !'],
      correctIndex: 0,
      wrongExplanation: '"Mhoro!" is the correct greeting reply. "Chisarai" means stay well (goodbye), "Ndinotenda" means thank you.',
      wrongExplanationFr: '"Mhoro !" est la bonne réponse. "Chisarai" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'Makadii?',
      textTranslation: 'How are you? (formal)',
      textTranslationFr: 'Comment allez-vous ? (formel)',
    },
    {
      speaker: 'user',
      text: 'Ndiripowo, tatenda! Makadiiwo?',
      textTranslation: "I'm fine, thank you! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et vous ?',
      options: ['Ndiripowo, tatenda! Makadiiwo?', 'Handizivi.', 'Chisarai!'],
      optionsFr: ['Ndiripowo, tatenda ! Makadiiwo ?', 'Handizivi.', 'Chisarai !'],
      correctIndex: 0,
      wrongExplanation: '"Ndiripowo" means "I am fine." "Handizivi" means "I don\'t know" and "Chisarai" means goodbye.',
      wrongExplanationFr: '"Ndiripowo" signifie "Je vais bien." "Handizivi" signifie "Je ne sais pas".',
    },
  ],

  somali: (name) => [
    {
      speaker: 'guide',
      text: `Salaam, ${name}!`,
      textTranslation: `Hello (Peace), ${name}!`,
      textTranslationFr: `Bonjour (Paix), ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Wa calaykum assalaam!',
      textTranslation: 'And upon you peace! (reply to Salaam)',
      textTranslationFr: 'Et sur toi la paix ! (réponse à Salaam)',
      options: ['Wa calaykum assalaam!', 'Nabad gelyo!', 'Mahadsanid!'],
      optionsFr: ['Wa calaykum assalaam !', 'Nabad gelyo !', 'Mahadsanid !'],
      correctIndex: 0,
      wrongExplanation: '"Wa calaykum assalaam" is the correct reply to "Salaam". "Nabad gelyo" means goodbye, "Mahadsanid" means thank you.',
      wrongExplanationFr: '"Wa calaykum assalaam" est la bonne réponse. "Nabad gelyo" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'Sidee tahay?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Waan fiicnahay, mahadsanid! Adiguse?',
      textTranslation: "I'm fine, thank you! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et toi ?',
      options: ['Waan fiicnahay, mahadsanid! Adiguse?', 'Garanmayo.', 'Nabad gelyo!'],
      optionsFr: ['Waan fiicnahay, mahadsanid ! Adiguse ?', 'Garanmayo.', 'Nabad gelyo !'],
      correctIndex: 0,
      wrongExplanation: '"Waan fiicnahay" means "I am fine." "Garanmayo" means "I don\'t know" and "Nabad gelyo" means goodbye.',
      wrongExplanationFr: '"Waan fiicnahay" signifie "Je vais bien." "Garanmayo" signifie "Je ne sais pas".',
    },
  ],

  berber: (name) => [
    {
      speaker: 'guide',
      text: `Azul, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Azul fellak!',
      textTranslation: 'Hello to you! (reply to Azul)',
      textTranslationFr: 'Bonjour à toi ! (réponse à Azul)',
      options: ['Azul fellak!', 'Aqqa-k!', 'Tanemmirt!'],
      optionsFr: ['Azul fellak !', 'Aqqa-k !', 'Tanemmirt !'],
      correctIndex: 0,
      wrongExplanation: '"Azul fellak" means "Hello to you" — the correct reply. "Aqqa-k" means there you are (casual), "Tanemmirt" means thank you.',
      wrongExplanationFr: '"Azul fellak" signifie "Bonjour à toi" — la bonne réponse. "Tanemmirt" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Amek tllid?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Lhan, tanemmirt! Kečč?',
      textTranslation: 'Fine, thank you! And you?',
      textTranslationFr: 'Bien, merci ! Et toi ?',
      options: ['Lhan, tanemmirt! Kečč?', 'Ur ssineɣ.', 'Aqqa-k!'],
      optionsFr: ['Lhan, tanemmirt ! Kečč ?', 'Ur ssineɣ.', 'Aqqa-k !'],
      correctIndex: 0,
      wrongExplanation: '"Lhan" means "fine/well." "Ur ssineɣ" means "I don\'t know."',
      wrongExplanationFr: '"Lhan" signifie "bien." "Ur ssineɣ" signifie "Je ne sais pas".',
    },
  ],

  moore: (name) => [
    {
      speaker: 'guide',
      text: `Nee windiga, ${name}!`,
      textTranslation: `Good morning, ${name}!`,
      textTranslationFr: `Bonjour (matin), ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Nee windiga!',
      textTranslation: 'Good morning! (reply)',
      textTranslationFr: 'Bonjour (matin) ! (en retour)',
      options: ['Nee windiga!', 'Waongo!', 'Barka!'],
      optionsFr: ['Nee windiga !', 'Waongo !', 'Barka !'],
      correctIndex: 0,
      wrongExplanation: '"Nee windiga" is the correct morning greeting reply. "Waongo" means truth/really, and "Barka" means blessed/thank you in context.',
      wrongExplanationFr: '"Nee windiga" est la bonne réponse au salut du matin.',
    },
    {
      speaker: 'guide',
      text: 'Y meng a?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Laafi! Fo me?',
      textTranslation: 'Fine! And you?',
      textTranslationFr: 'Bien ! Et toi ?',
      options: ['Laafi! Fo me?', 'Mam yãmb ye.', 'Waongo!'],
      optionsFr: ['Laafi ! Fo me ?', 'Mam yãmb ye.', 'Waongo !'],
      correctIndex: 0,
      wrongExplanation: '"Laafi" means "fine/in good health." "Mam yãmb ye" means "I don\'t know."',
      wrongExplanationFr: '"Laafi" signifie "bien/en bonne santé." "Mam yãmb ye" signifie "Je ne sais pas".',
    },
  ],

  lingala: (name) => [
    {
      speaker: 'guide',
      text: `Mbote, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Mbote!',
      textTranslation: 'Hello! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Mbote!', 'Tozali!', 'Merci mingi!'],
      optionsFr: ['Mbote !', 'Tozali !', 'Merci mingi !'],
      correctIndex: 0,
      wrongExplanation: '"Mbote!" is the correct greeting. "Tozali" means we are (here), "Merci mingi" means many thanks.',
      wrongExplanationFr: '"Mbote !" est la bonne réponse. "Merci mingi" signifie beaucoup de remerciements.',
    },
    {
      speaker: 'guide',
      text: 'Ozali malamu?',
      textTranslation: 'Are you well?',
      textTranslationFr: 'Allez-vous bien ?',
    },
    {
      speaker: 'user',
      text: 'Nazali malamu, merci! Yo mpe?',
      textTranslation: "I'm well, thanks! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et toi ?',
      options: ['Nazali malamu, merci! Yo mpe?', 'Nakoloba te.', 'Tosambo!'],
      optionsFr: ['Nazali malamu, merci ! Yo mpe ?', 'Nakoloba te.', 'Tosambo !'],
      correctIndex: 0,
      wrongExplanation: '"Nazali malamu" means "I am well." "Nakoloba te" means "I won\'t say/I don\'t know."',
      wrongExplanationFr: '"Nazali malamu" signifie "Je vais bien." "Nakoloba te" signifie "Je ne sais pas".',
    },
  ],

  twi: (name) => [
    {
      speaker: 'guide',
      text: `Akwaaba, ${name}!`,
      textTranslation: `Welcome, ${name}!`,
      textTranslationFr: `Bienvenue, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Medaase!',
      textTranslation: 'Thank you! (for welcoming me)',
      textTranslationFr: 'Merci ! (pour l\'accueil)',
      options: ['Medaase!', 'Nante yie!', 'Maakyia!'],
      optionsFr: ['Medaase !', 'Nante yie !', 'Maakyia !'],
      correctIndex: 0,
      wrongExplanation: '"Medaase" (thank you) is the correct reply to "Akwaaba" (welcome). "Nante yie" means walk well (goodbye), "Maakyia" means good afternoon.',
      wrongExplanationFr: '"Medaase" (merci) est la bonne réponse à "Akwaaba" (bienvenue). "Nante yie" signifie au revoir.',
    },
    {
      speaker: 'guide',
      text: 'Wo ho te sɛn?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Me ho yɛ, meda ase! Na wo ho?',
      textTranslation: 'I am fine, thank you! And you?',
      textTranslationFr: 'Je vais bien, merci ! Et toi ?',
      options: ['Me ho yɛ, meda ase! Na wo ho?', 'Mente aseɛ.', 'Nante yie!'],
      optionsFr: ['Me ho yɛ, meda ase ! Na wo ho ?', 'Mente aseɛ.', 'Nante yie !'],
      correctIndex: 0,
      wrongExplanation: '"Me ho yɛ" means "I am fine." "Mente aseɛ" means "I don\'t understand" and "Nante yie" means goodbye.',
      wrongExplanationFr: '"Me ho yɛ" signifie "Je vais bien." "Nante yie" signifie au revoir.',
    },
  ],

  chichewa: (name) => [
    {
      speaker: 'guide',
      text: `Moni, ${name}!`,
      textTranslation: `Hello, ${name}!`,
      textTranslationFr: `Bonjour, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Moni!',
      textTranslation: 'Hello! (greeting back)',
      textTranslationFr: 'Bonjour ! (en retour)',
      options: ['Moni!', 'Tionana!', 'Zikomo!'],
      optionsFr: ['Moni !', 'Tionana !', 'Zikomo !'],
      correctIndex: 0,
      wrongExplanation: '"Moni!" is the correct greeting reply. "Tionana" means see you later, and "Zikomo" means thank you.',
      wrongExplanationFr: '"Moni !" est la bonne réponse. "Tionana" signifie à bientôt, "Zikomo" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Muli bwanji?',
      textTranslation: 'How are you? (formal)',
      textTranslationFr: 'Comment allez-vous ? (formel)',
    },
    {
      speaker: 'user',
      text: 'Ndili bwino, zikomo! Kaya inu?',
      textTranslation: "I'm fine, thank you! And you?",
      textTranslationFr: 'Je vais bien, merci ! Et vous ?',
      options: ['Ndili bwino, zikomo! Kaya inu?', 'Sindikudziwa.', 'Tionana!'],
      optionsFr: ['Ndili bwino, zikomo ! Kaya inu ?', 'Sindikudziwa.', 'Tionana !'],
      correctIndex: 0,
      wrongExplanation: '"Ndili bwino" means "I am fine." "Sindikudziwa" means "I don\'t know" and "Tionana" means see you later.',
      wrongExplanationFr: '"Ndili bwino" signifie "Je vais bien." "Sindikudziwa" signifie "Je ne sais pas".',
    },
  ],

  wolof: (name) => [
    {
      speaker: 'guide',
      text: `Salaam aleekum, ${name}!`,
      textTranslation: `Peace be upon you, ${name}!`,
      textTranslationFr: `La paix soit sur toi, ${name} !`,
    },
    {
      speaker: 'user',
      text: 'Aleekum salaam!',
      textTranslation: 'And upon you peace! (reply)',
      textTranslationFr: 'Et sur toi la paix ! (réponse)',
      options: ['Aleekum salaam!', 'Ba beneen yoon!', 'Jërejëf!'],
      optionsFr: ['Aleekum salaam !', 'Ba beneen yoon !', 'Jërejëf !'],
      correctIndex: 0,
      wrongExplanation: '"Aleekum salaam" is the correct reply to "Salaam aleekum." "Ba beneen yoon" means see you next time, "Jërejëf" means thank you.',
      wrongExplanationFr: '"Aleekum salaam" est la bonne réponse. "Ba beneen yoon" signifie à la prochaine, "Jërejëf" signifie merci.',
    },
    {
      speaker: 'guide',
      text: 'Nanga def?',
      textTranslation: 'How are you?',
      textTranslationFr: 'Comment allez-vous ?',
    },
    {
      speaker: 'user',
      text: 'Mangi fi rekk, jërejëf! Yow?',
      textTranslation: "I'm here/fine, thanks! And you?",
      textTranslationFr: 'Je suis là, merci ! Et toi ?',
      options: ['Mangi fi rekk, jërejëf! Yow?', 'Xam-xam duma ko.', 'Ba beneen yoon!'],
      optionsFr: ['Mangi fi rekk, jërejëf ! Yow ?', 'Xam-xam duma ko.', 'Ba beneen yoon !'],
      correctIndex: 0,
      wrongExplanation: '"Mangi fi rekk" means "I am right here/fine." "Xam-xam duma ko" means "I don\'t know it."',
      wrongExplanationFr: '"Mangi fi rekk" signifie "Je suis là/bien." "Xam-xam duma ko" signifie "Je ne sais pas".',
    },
  ],
};

// Fallback generic script
const fallbackScript: LangScript = (name) => [
  {
    speaker: 'guide',
    text: `Hello, ${name}!`,
    textTranslation: `Hello, ${name}!`,
    textTranslationFr: `Bonjour, ${name} !`,
  },
  {
    speaker: 'user',
    text: 'Hello!',
    textTranslation: 'Hello! (greeting back)',
    textTranslationFr: 'Bonjour ! (en retour)',
    options: ['Hello!', 'Goodbye!', 'Thank you!'],
    optionsFr: ['Hello !', 'Au revoir !', 'Merci !'],
    correctIndex: 0,
    wrongExplanation: '"Hello!" is the correct greeting reply.',
    wrongExplanationFr: '"Hello !" est la bonne réponse.',
  },
  {
    speaker: 'guide',
    text: 'How are you?',
    textTranslation: 'How are you?',
    textTranslationFr: 'Comment allez-vous ?',
  },
  {
    speaker: 'user',
    text: "I'm fine, thank you! And you?",
    textTranslation: "I'm fine, thank you! And you?",
    textTranslationFr: 'Je vais bien, merci ! Et toi ?',
    options: ["I'm fine, thank you! And you?", "I don't know.", 'Goodbye!'],
    optionsFr: ['Je vais bien, merci ! Et toi ?', "Je ne sais pas.", 'Au revoir !'],
    correctIndex: 0,
    wrongExplanation: '"I\'m fine, thank you" is the correct polite reply.',
    wrongExplanationFr: '"Je vais bien, merci" est la bonne réponse polie.',
  },
];

/**
 * Returns a conversation script for the given language, with the user's name
 * injected into the guide's opening line.
 * @param languageId  - e.g. 'igbo', 'swahili'
 * @param userName    - display name of the authenticated user, or 'Friend' as default
 */
export function getConversationScript(
  languageId: string,
  userName: string,
): ConversationTurn[] {
  const fn = scripts[languageId] ?? fallbackScript;
  return fn(userName);
}
